version: '3'

services:
  web:
    build: .
    ports:
      - "6000:5000"
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: always