"""add region and circle fields

Revision ID: 0a4f72fd866c
Revises: 9545e511904f
Create Date: 2025-01-21 23:01:04.611899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4f72fd866c'
down_revision = '9545e511904f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=True))

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('post_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hometown_province_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hometown_city_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hometown_district_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_province_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_city_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_district_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_profile_completed', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'region', ['hometown_city_id'], ['id'])
        batch_op.create_foreign_key(None, 'region', ['current_city_id'], ['id'])
        batch_op.create_foreign_key(None, 'region', ['current_province_id'], ['id'])
        batch_op.create_foreign_key(None, 'region', ['hometown_province_id'], ['id'])
        batch_op.create_foreign_key(None, 'region', ['current_district_id'], ['id'])
        batch_op.create_foreign_key(None, 'region', ['hometown_district_id'], ['id'])
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_profile_completed')
        batch_op.drop_column('current_district_id')
        batch_op.drop_column('current_city_id')
        batch_op.drop_column('current_province_id')
        batch_op.drop_column('hometown_district_id')
        batch_op.drop_column('hometown_city_id')
        batch_op.drop_column('hometown_province_id')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('post_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
